---
- name: Deploy Scientific Calculator Microservice
  hosts: local_host
  become: yes

  tasks:
    - name: Login to Docker Hub
      shell: "echo {{ docker_password }} | docker login -u {{ docker_user }} --password-stdin"
      changed_when: false

    - name: Pull latest image from Docker Hub
      docker_image:
        name: "siddheshmahajan/scientific_calculator"
        tag: latest
        source: pull

    - name: Stop and remove old container if it exists
      docker_container:
        name: calculator_service
        state: absent

    - name: Run the new Calculator container
      docker_container:
        name: calculator_service
        image: "siddheshmahajan/scientific_calculator:latest"
        state: started
        restart_policy: unless-stopped
        ports:
          - "8081:8080" # Maps Host port 8081 to Container port 8080