---
- name: Deploy Scientific Calculator Container
  hosts: local_host
  become: yes

  # These variables are populated by the --extra-vars passed from Jenkins
  vars:
    docker_user: "{{ docker_user }}"
    docker_password: "{{ docker_password }}"
    image_name: "scientific_calculator"

  tasks:
    - name: Login to Docker Hub
      shell: "echo {{ docker_password }} | docker login -u {{ docker_user }} --password-stdin"

    - name: Pull the latest Docker image
      docker_image:
        name: "{{ docker_user }}/{{ image_name }}:latest"
        source: pull

    - name: Ensure existing container is stopped and removed
      docker_container:
        name: "{{ image_name }}"
        state: absent

    - name: Run the new container
      docker_container:
        name: "{{ image_name }}"
        image: "{{ docker_user }}/{{ image_name }}:latest"
        state: started
        interactive: yes
        tty: yes
        restart_policy: always
